public enum Sounds
{
    JUMPING,
    PICKUP_COIN,
    BREAK_BLOCK,
    PIPE_TRAVEL,
    FAILED_BREAK,
    PICKUP_POWERUP,
    POWERUP_APPEARS,
    PLAYER_DIES,
    TIME_WARNING,
    STAGE_CLEAR,
    GAME_OVER,
    KICKING,
    FIREWORKS
}
